# -*- coding: utf-8 -*-
"""Chatbot_websites.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N4ZdY_bka9InK0PXOzlZjxa3XjUTOjg8
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')

# %cd /gdrive/My\ Drive/Chatbot

# %ls

!pip install langchain
!pip install faiss-cpu
!pip install openai
!pip install unstructured
!pip install pdf2image
!pip install tiktoken
!pip install InstructorEmbedding
!pip install sentence_transformers
!pip install nest_asyncio

from langchain.document_loaders import UnstructuredURLLoader
from langchain.document_loaders.sitemap import SitemapLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceInstructEmbeddings
from langchain.chains import RetrievalQAWithSourcesChain
from langchain.chains.question_answering import load_qa_chain
from langchain.chat_models import ChatOpenAI
import nest_asyncio
import faiss
import pickle
import pandas as pd
import os

nest_asyncio.apply()
os.environ['OPENAI_API_KEY'] = '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'
df = pd.read_csv('pages.csv')
# urls = list(df['URL'])
# urls = [
    # 'https://langchain.readthedocs.io/'
    # 'https://www.ssense.com/sitemap.xml'
    # 'https://www.homedepot.com/sitemap/P/PIPs/25T/025-011-0.xml'
    # 'https://lmsys.org/blog/2023-03-30-vicuna/',
    # 'https://www.interviewbit.com/javascript-cheat-sheet/'
# ]

print(df.shape)
df['sitemap'] = df['URL'].apply(lambda x: x.find('/b/') != -1)
df_sitemap = df[df['sitemap'] != False]
print(df_sitemap.shape)

df_sitemap.iloc[56231]

# loaders = UnstructuredURLLoader(urls=urls)
# data = loaders.load()
# data[:-10]
# sitemap_loader = SitemapLoader(web_path="https://langchain.readthedocs.io/sitemap.xml")
sitemap_loader = SitemapLoader(web_path="https://www.ssense.com/en-us/sitemap")
docs = sitemap_loader.load()

# Text Splitter
# text_splitter = CharacterTextSplitter(separator='\n',
#                                     chunk_size=1000,
#                                     chunk_overlap=200)
# docs = text_splitter.split_documents(docs)
print(len(docs))

embeddings = HuggingFaceInstructEmbeddings(model_name='hkunlp/instructor-xl')
embeddings

# Save the embeddings into a vector database
vectorStore_openAI = FAISS.from_documents(docs, embeddings)
with open("faiss_store_homedepot.pkl", "wb") as f:
    pickle.dump(vectorStore_openAI, f)

with open("faiss_store_homedepot.pkl", "rb") as f:
        VectorStore = pickle.load(f)

llm = ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')
chain = RetrievalQAWithSourcesChain.from_llm(llm=llm, retriever=VectorStore.as_retriever())

llm

chain({"question": "Do you know langchain?"}, return_only_outputs=True)

chain({"question": "Then can you please tell me who made langchain?"}, return_only_outputs=True)

chain({"question": "What kinds of features do langchain have?"}, return_only_outputs=True)

chain({"question": "How to evaluate a Chatbot?"}, return_only_outputs=True)