# -*- coding: utf-8 -*-
"""SiteMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1odzxXhMD61Tqlhj3NTPwBkzNk4kS6XAP
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')

# %cd /gdrive/My\ Drive/Chatbot

# %ls

!pip install ultimate-sitemap-parser

#!/usr/bin/env python3


import csv, requests
from usp.tree import sitemap_tree_for_homepage
import pandas as pd
from concurrent.futures import ThreadPoolExecutor

tree = sitemap_tree_for_homepage('https://www.ssense.com/')

# pageDetails = [[
#     page.url,
#     page.last_modified.isoformat('#','hours').split('#')[0] if page.last_modified else None,
#     float(page.priority) if page.priority else None] for page in tree.all_pages()]

# with open('pages.csv', 'w+', newline='') as fl:
#     write = csv.writer(fl)
#     write.writerow(['URL', 'LastModified', 'Priority'])
#     write.writerows(pageDetails)

# print(f'{len(pageDetails)} rows founded!')

for tr in tree.all_pages():
  print(tr)

'''
with open('pages.csv') as csvFile:
    csvReader = csv.reader(csvFile, delimiter=',')
    print([row[0] for row in csvReader][1:10])
'''

df = pd.read_csv('pages.csv')
df.head()

df['URL']

# https://pythontic.com/pandas/dataframe-attributes/introduction
print(df.shape)
df['sitemap'] = df['URL'].apply(lambda x: x.find('bath') != -1)
df_sitemap = df[df['sitemap'] != False]
print(df_sitemap.shape)

def callbackResp(cll):
    response = cll.result()
    df['Status'] = response.status_code
    df['Redirected'] = response.is_redirect
    df['PermanentRedirection'] = response.is_permanent_redirect
    df['IssueReason'] = response.reason if response.reason != 'OK' else None

with ThreadPoolExecutor(max_workers=1) as executor:
    for url in df['URL']:
        cll = executor.submit(requests.head, url)
        cll.add_done_callback(callbackResp)
        if(cll.running()):
            print('Task 1 running')
            print()
        elif(cll.done()):
            print(cll.result())
            break

df.head()

print(df.columns)
print(list(set(df['Priority'])))
print(list(set(df['Status'])))
print(list(set(df['Redirected'])))
print(list(set(df['PermanentRedirection'])))
print(list(set(df['IssueReason'])))

df.loc[df.Priority > 0.6]

# df['Status'].value_counts()
df[['URL', 'Status']].head(10)

df['Status'] = (pd
    .Categorical(
        df['Status'],
        categories=list(set(df['Status'])),
        ordered=False))

df['Priority'] = (pd
    .Categorical(
        df['Priority'],
        categories=[float(i/10) for i in range(0,10,1)],
        ordered=True))

df['Redirected'] = (pd
    .Categorical(
        df['Redirected'],
        categories=list(set(df['Redirected'])),
        ordered=False))

df['PermanentRedirection'] = (pd
    .Categorical(
        df['PermanentRedirection'],
        categories=list(set(df['PermanentRedirection'])),
        ordered=False))

df[['URL', 'Status','Priority']].sample(5)

df.to_csv('sitemap.csv', index=False)

